$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
console_title_template: "🥷{{.UserName}} :: {{.Shell}} in {{.Folder}}"
version: 2
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        style: plain
        foreground: '#00FFFF'
        foreground_templates: [
          "{{if eq .Shell \"bash\" }}#FFFFFF{{end}}"
        ]
        template: "{{ if eq .Shell \"bash\" }}  {{ end }}{{ if .WSL }} at {{.Icon}} {{ else if eq .Shell \"pwsh\" }} {{.Icon}}{{ end }}"
        properties:
          windows: ' '
      - type: path
        background: '#29315A'
        foreground: '#C4A000'
        leading_diamond: 
        properties:
          style: "agnoster_short"
          folder_separator_icon: "/"
          hide_root_location: true
          max_depth: 2
        style: diamond
        template: ' {{ .Path }}'
        trailing_diamond: 
      - type: git
        background: '#29315A'
        foreground: '#43CCEA'
        foreground_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}'
          - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
          - '{{ if gt .Behind 0 }}#B388FF{{ end }}'
        leading_diamond: ' '
        properties:
          branch_max_length: 10
          truncate_symbol: '...'
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        style: diamond
        template: "{{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus 
                   }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and 
                   (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if 
                   .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if 
                   gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
        trailing_diamond: 
      - type: status
        style: plain
        foreground: '#FFFFFF'
        foreground_templates:
          - '{{ if gt .Code 0 }}#e91e63{{ end }}'
        template: '  {{ if gt .Code 0 }}{{ .Code }}{{ end }}'
        properties:
          always_enabled: true
  - type: prompt
    alignment: right
    segments:
      - type: node
        foreground: '#5fb157'
        properties:
          display_mode: files
          fetch_package_manager: true
          fetch_version: true
          npm_icon: '<#FE4A49> npm</> '
          yarn_icon: '<#44FFD2> yarn</> '
        style: plain
        template: " {{ .Full }}"
      - type: python
        foreground: '#FED142'
        properties:
          display_mode: context
          fetch_virtual_env: false
        style: plain
        template: ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
      - type: angular
        foreground: "#000000"
        template: "  {{ .Full }} "
      - type: java
        foreground: "#CC0000"
        template: "  {{ .Full }}"
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        foreground: '#63F08C'
        style: plain
        template: ' ➜ '

